# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os
import cv2

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import QPalette, QBrush, QPixmap
import yoloCustomObjectDetection as yolo

class Ui_Form(QWidget):  
    def setupUi(self, Form):
        Form.resize(1280,720)
        self.cap = cv2.VideoCapture(0)
        self.playerTimer = QTimer()
        self.playerTimer.timeout.connect(self.getImage)
        self.detector = yolo.MugDetection(capture_index=0, model_name='yolov5m.pt')


        self.button_open_camera = QtWidgets.QPushButton(u'打开相机')


        # 信息显示,label_show_camera为显示经过处理后的摄像头抓取画面
        self.label_show_camera = QtWidgets.QLabel(Form)

        self.label_show_camera.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.label_show_camera.setAutoFillBackground(False)

        #设置result label外形
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(26)
        self.label_show_result = QtWidgets.QLabel(Form)
        self.label_show_result.setGeometry(QtCore.QRect(100,500,320,70))
        self.label_show_result.setText("You are wearing mask")
        self.label_show_result.setFont(font)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

#通过yoloCustomObjectDetection获取一张处理后的图片
    def getImage(self):
        assert self.cap.isOpened()
        frame = self.detector(self.cap)
        show = cv2.resize(frame,(640,480))
        show = cv2.cvtColor(show, cv2.COLOR_BGR2RGB)
        showImage = QtGui.QImage(show.data, show.shape[1], show.shape[0], QtGui.QImage.Format_RGB888)
        self.label_show_camera.setPixmap(QtGui.QPixmap.fromImage(showImage))

        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.__init__()
    ui.setupUi(Form)
    ui.playerTimer.start(0)#计时器开始计时，每次计时结束调用一次获取并显示图像
    Form.show()
    sys.exit(app.exec())





